project_id = "jseyxxsptcckjumjcljk"

[functions.admin-create-user]
# Keep JWT verification enabled for admin-only access

[functions.razorpay-payment]
# Keep JWT verification enabled for secure payment processing

[functions.validate-payment-gateways]
verify_jwt = false

[functions.ekqr-payment]
# Keep JWT verification enabled for secure payment processing