project_id = "jseyxxsptcckjumjcljk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ekqr-payment]
verify_jwt = false

[functions.ekqr-webhook]
verify_jwt = false

[functions.payment-recovery]
verify_jwt = false

[functions.razorpay-payment]
verify_jwt = false

[functions.validate-payment-gateways]
verify_jwt = false

[functions.subscription-payment]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = false

[functions.gemini-ai]
verify_jwt = false

[functions.send-sms]
verify_jwt = false