// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jseyxxsptcckjumjcljk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZXl4eHNwdGNja2p1bWpjbGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzU1MjAsImV4cCI6MjA2NzYxMTUyMH0.liM5Iq6IT3LwY6GlWLy3FbdUdyPwQLcsrnWVW9nqy8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});